version: '3'
services: 
  web:
    container_name: checkrs-app
    build: .
    volumes: 
      - .:/app/
      - /node_modules
    ports: 
      - "3000:3000"
    depends_on:
      - postgres
    env_file: 
      - .env
    restart: always
  postgres:
    container_name: checkrs-db
    image: postgres:9.6.2-alpine
    env_file:
      - .env
    restart: always
